import type { Metadata } from "next";
import { PublicSiteShell } from "@/components/public-site-shell";
import { caseStudy } from "@/lib/public-content";

export const metadata: Metadata = { title: caseStudy.title, description: caseStudy.description, alternates: { canonical: "/case-studies/customer-support-agent-safety" }, openGraph: { type: "article", title: caseStudy.title, description: caseStudy.description, url: "/case-studies/customer-support-agent-safety" } };

export default function CustomerSupportCaseStudyPage() {
  const structuredData = { "@context": "https://schema.org", "@type": "Article", headline: caseStudy.title, description: caseStudy.description, datePublished: caseStudy.updatedAt, dateModified: caseStudy.updatedAt, mainEntityOfPage: "https://agent-proof.dev/case-studies/customer-support-agent-safety", author: { "@type": "Organization", name: "AgentProof" } };
  return <PublicSiteShell><main className="mx-auto max-w-3xl px-6 py-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><span className="eyebrow">CONTROLLED CASE STUDY</span><h1 className="mt-4 font-mono text-3xl font-bold uppercase md:text-5xl">{caseStudy.title}</h1><p className="mt-6 border-l-2 border-[var(--color-seal-indigo)] pl-4 text-lg leading-8 text-[var(--color-on-surface-variant)]">{caseStudy.summary}</p><section className="mt-12 border border-[var(--color-outline-variant)] bg-[var(--color-paper-cream)] p-6"><span className="eyebrow">MEASURED RESULT</span><div className="mt-4 grid gap-4 sm:grid-cols-3"><strong className="font-mono text-3xl">14<br /><small className="text-xs text-[var(--color-on-surface-variant)]">SCENARIOS</small></strong><strong className="font-mono text-3xl text-[var(--color-pass-moss)]">12<br /><small className="text-xs text-[var(--color-on-surface-variant)]">PASSED</small></strong><strong className="font-mono text-3xl text-[var(--color-evidence-amber)]">2<br /><small className="text-xs text-[var(--color-on-surface-variant)]">FINDINGS</small></strong></div></section><section className="legal-copy mt-10"><h2>What the verification found</h2><ul>{caseStudy.findings.map((finding) => <li key={finding}>{finding}</li>)}</ul><p>This is a controlled demonstration using an AgentProof test agent. It does not represent an independent customer result or a claim about every support agent.</p></section></main></PublicSiteShell>;
}
