import { AppShell } from "@/components/app-shell";
import { ActionButton, ContractWindow, EvidenceLedger, EvidenceRow, MetricStrip, PageHeader, ProofPanel } from "@/components/proof-ui";
import { StatusPill } from "@/components/status-pill";
import { VerificationStamp } from "@/components/verification-stamp";
import { sampleAgents, samplePublicReport } from "@/lib/sample-data";

export default async function AgentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const agent = sampleAgents.find((item) => item.id === id) ?? sampleAgents[0]; const report = samplePublicReport;
  return <AppShell><div className="product-page">
    <PageHeader eyebrow="AGENT DOSSIER" title={agent.name} description="The current operational contract, latest verification status, and issued evidence for this deployment." meta={<><span>REGISTRY / {agent.id}</span><span>ENDPOINT / {agent.endpointUrl}</span><StatusPill status={agent.latestStatus} /></>} actions={<><ActionButton variant="quiet" href={`/verify/${report.publicId}`}>Public report</ActionButton><ActionButton href={`/agents/${agent.id}/run`}>Run verification</ActionButton></>} />
    <MetricStrip metrics={[{ label: "Reliability score", value: `${agent.overallScore ?? 0}/100`, tone: "pass" }, { label: "Tests executed", value: String(report.totalTests) }, { label: "Critical failures", value: String(report.critical), tone: "pass" }, { label: "Valid until", value: report.validUntil }]} />
    <div className="split-layout"><div className="artifact-stack"><ContractWindow><pre>{`{\n  "agent": "${agent.name}",\n  "version": "${agent.currentVersion}",\n  "capabilities": [\n    "check_availability",\n    "create_booking",\n    "reschedule"\n  ],\n  "restrictions": [\n    "never disclose diagnosis",\n    "always check calendar first"\n  ]\n}`}</pre></ContractWindow><ProofPanel><div className="section-kicker">RECENT VERIFICATION RUNS</div><EvidenceLedger title="RUN / SCORE / STATUS">{[{ id: "RUN-8891", title: "22 AUG 2026 / full matrix", state: "PASS" as const, detail: "179 of 184 assertions passed · 94/100" }, { id: "RUN-8840", title: "15 AUG 2026 / full matrix", state: "PASS" as const, detail: "172 of 184 assertions passed · 91/100" }, { id: "RUN-8792", title: "01 AUG 2026 / full matrix", state: "WARN" as const, detail: "145 of 184 assertions passed · 76/100" }].map((run) => <EvidenceRow key={run.id} id={run.id} category="RUN" title={run.title} state={run.state} detail={run.detail} />)}</EvidenceLedger></ProofPanel></div><div className="artifact-stack"><ProofPanel dark className="stamp-panel"><span className="eyebrow" style={{ color: "#d8b17d" }}>AGENTPROOF VERIFIED</span><VerificationStamp status={agent.latestStatus} size={150} /><strong className="stamp-panel__name">{agent.name}</strong><span className="stamp-panel__meta">Version {agent.currentVersion} / Standard v1.4</span></ProofPanel><ProofPanel><div className="section-kicker">PUBLIC BADGE</div><p className="body-md" style={{ color: "var(--muted)", margin: "12px 0" }}>Publish a plain-language status page for buyers and users.</p><code className="embed-code">&lt;AgentProofBadge agentId=&quot;{agent.id}&quot; /&gt;</code><ActionButton variant="quiet" href={`/verify/${report.publicId}`} icon={null}>Inspect public report</ActionButton></ProofPanel></div></div>
  </div></AppShell>;
}
