"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { ArrowLeft, Mail, Eye, EyeOff, User, ArrowRight, ShieldCheck, Zap, Activity } from "lucide-react";

export default function SignUpPage() {
  const [showPassword, setShowPassword] = useState(false);
  return <main className="lp-split-auth"><div className="lp-split-auth__left"><header className="lp-split-auth__header"><Link href="/" className="lp-split-auth__logo"><Image src="/logo-agentproof.png" alt="AgentProof" width={140} height={32} style={{ objectFit: "contain" }} /></Link><Link href="/" className="lp-split-auth__back"><ArrowLeft size={16} />Back to Home</Link></header><div className="lp-split-auth__form-wrapper"><div className="lp-split-auth__form-header"><h1 className="lp-split-auth__title">Request Access</h1><p className="lp-split-auth__subtitle">Submit credentials for initial verification.</p></div><form onSubmit={(e) => e.preventDefault()} className="lp-auth-form"><div className="lp-auth-form__group"><label htmlFor="name-up">Full Name</label><div className="lp-auth-form__input-wrapper"><input id="name-up" type="text" placeholder="John Doe" /><User className="lp-auth-form__icon" size={18} /></div></div><div className="lp-auth-form__group"><label htmlFor="email-up">Email Address</label><div className="lp-auth-form__input-wrapper"><input id="email-up" type="email" placeholder="user@example.com" /><Mail className="lp-auth-form__icon" size={18} /></div></div><div className="lp-auth-form__group"><label htmlFor="password-up">Password</label><div className="lp-auth-form__input-wrapper"><input id="password-up" type={showPassword ? "text" : "password"} placeholder="••••••••" /><button type="button" className="lp-auth-form__icon-btn" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div><p className="lp-auth-form__terms">By submitting this request, you agree to our <Link href="#">Methodology</Link> and <Link href="#">Terms of Service</Link>.</p><button type="submit" className="lp-btn lp-btn--primary lp-auth-form__submit" style={{ background: "var(--ink-graphite)", color: "var(--paper-cream)" }}>Submit Request<ArrowRight size={18} /></button><p className="lp-auth-form__switch">Already have access? <Link href="/auth/sign-in">Initialize session</Link></p></form></div><footer className="lp-split-auth__footer">© 2026 AgentProof. Forensic Authority in AI Verification.</footer></div><div className="lp-split-auth__right"><Image src="/auth-bg.jpg" alt="" fill priority style={{ objectFit: "cover", zIndex: 0 }} /><div className="lp-split-auth__right-inner"><div className="lp-auth-deliverables"><Deliverable icon={<ShieldCheck size={24} />} title="Immutable Audits" copy="Every tool call and state change is cryptographically hashed for complete transparency." /><Deliverable icon={<Zap size={24} />} title="Automated Adversarial Testing" copy="Stop prompt-guessing. We generate thousands of edge cases to verify boundaries." /><Deliverable icon={<Activity size={24} />} title="Live Telemetry" copy="Monitor your agent's reliability score in real-time as it interacts with users." /></div></div></div></main>;
}

function Deliverable({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="lp-auth-deliverable"><div className="lp-auth-deliverable__icon">{icon}</div><div><h4>{title}</h4><p>{copy}</p></div></div>; }
