"use client";

import Image from "next/image";
import { useState } from "react";
import { ActionButton, EvidenceLedger, EvidenceRow, ReportMetaGrid, ReportSheet } from "@/components/proof-ui";
import { StatusPill } from "@/components/status-pill";
import { VerificationStamp } from "@/components/verification-stamp";
import { samplePublicReport } from "@/lib/sample-data";

export default function PublicReportPage() { const report = samplePublicReport; const [show, setShow] = useState(false); return <main className="page-shell"><div className="public-report product-page"><Image src="/logo-agentproof.png" alt="AgentProof" width={140} height={34} priority style={{ mixBlendMode: "multiply" }} /><ReportSheet><div className="report-sheet__hero"><VerificationStamp status={report.status} size={150} /><div><div className="status-line"><span>OFFICIAL PUBLIC REPORT</span><StatusPill status={report.status} /></div><h1 className="report-sheet__title">{report.agentName} <span className="mono">v{report.agentVersion}</span></h1><div className="report-sheet__score">{report.score.overallScore}<small>/100</small></div><span className="eyebrow">AGENTPROOF VERIFIED</span></div></div><ReportMetaGrid items={[{ label: "Last verified", value: report.lastVerified }, { label: "Valid until", value: report.validUntil }, { label: "Scenarios tested", value: String(report.totalTests) }, { label: "Passed", value: `${report.passed} / ${report.totalTests}` }]} /><div className="public-report__actions"><ActionButton variant="quiet" onClick={() => setShow((current) => !current)} icon={<span>{show ? "↑" : "↓"}</span>}>{show ? "Hide evidence" : "View evidence"}</ActionButton></div></ReportSheet><section className="public-report__section"><span className="eyebrow">WHAT WAS TESTED?</span><h2>Behavior under real pressure</h2><div className="tested-list">{report.whatWasTested.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></section>{show && <EvidenceLedger title="PUBLIC EVIDENCE SUMMARY"><EvidenceRow id="E-01" category="RESULT" title="The agent completed the booking and safety matrix." state="PASS" detail={`${report.passed} scenarios passed. One minor fallback issue was recorded.`} /><EvidenceRow id="E-02" category="NOTE" title="A temporary availability failure produced a vague fallback." state="WARN" detail="This did not create a critical safety or policy failure." /></EvidenceLedger>}</div></main>; }
