"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { ArrowLeft, Mail, Eye, EyeOff, ArrowRight, ShieldCheck, Zap, Activity } from "lucide-react";

export default function SignInPage() {
  const [showPassword, setShowPassword] = useState(false);
  return <main className="lp-split-auth"><div className="lp-split-auth__left"><header className="lp-split-auth__header"><Link href="/" className="lp-split-auth__logo"><Image src="/logo-agentproof.png" alt="AgentProof" width={140} height={32} style={{ objectFit: "contain" }} /></Link><Link href="/" className="lp-split-auth__back"><ArrowLeft size={16} />Back to Home</Link></header><div className="lp-split-auth__form-wrapper"><div className="lp-split-auth__form-header"><h1 className="lp-split-auth__title">Access Portal</h1><p className="lp-split-auth__subtitle">Enter your credentials to access verified evidence.</p></div><form onSubmit={(e) => e.preventDefault()} className="lp-auth-form"><div className="lp-auth-form__group"><label htmlFor="email">Email Address</label><div className="lp-auth-form__input-wrapper"><input id="email" type="email" placeholder="user@example.com" /><Mail className="lp-auth-form__icon" size={18} /></div></div><div className="lp-auth-form__group"><label htmlFor="password">Password</label><div className="lp-auth-form__input-wrapper"><input id="password" type={showPassword ? "text" : "password"} placeholder="••••••••" /><button type="button" className="lp-auth-form__icon-btn" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div><div className="lp-auth-form__actions"><label className="lp-auth-form__checkbox"><input type="checkbox" /><span>Retain Session</span></label><Link href="#" className="lp-auth-form__forgot">Reset Key?</Link></div><button type="submit" className="lp-btn lp-btn--primary lp-auth-form__submit">Initialize Session<ArrowRight size={18} /></button><p className="lp-auth-form__switch">Don&apos;t have access? <Link href="/auth/sign-up">Request access</Link></p></form></div><footer className="lp-split-auth__footer">© 2026 AgentProof. Forensic Authority in AI Verification.</footer></div><AuthVisual /></main>;
}

function AuthVisual() { return <div className="lp-split-auth__right"><Image src="/auth-bg.jpg" alt="" fill priority style={{ objectFit: "cover", zIndex: 0 }} /><div className="lp-split-auth__right-inner"><div className="lp-auth-deliverables"><Deliverable icon={<ShieldCheck size={24} />} title="Immutable Audits" copy="Every tool call and state change is cryptographically hashed for complete transparency." /><Deliverable icon={<Zap size={24} />} title="Automated Adversarial Testing" copy="Stop prompt-guessing. We generate thousands of edge cases to verify boundaries." /><Deliverable icon={<Activity size={24} />} title="Live Telemetry" copy="Monitor your agent's reliability score in real-time as it interacts with users." /></div></div></div>; }
function Deliverable({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="lp-auth-deliverable"><div className="lp-auth-deliverable__icon">{icon}</div><div><h4>{title}</h4><p>{copy}</p></div></div>; }
